# Generated by Django 5.2 on 2025-11-28 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='query',
            field=models.TextField(blank=True, null=True),
        ),
    ]
